version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/foodman
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
